//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanBachHoa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Don_Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Don_Hang()
        {
            this.Chi_Tiet_Don_Hang = new HashSet<Chi_Tiet_Don_Hang>();
        }

        [Display(Name = "Mã Đơn Hàng")]
        public int id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Người Đặt")]
        public string ten { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "SDT")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Email")]
        public string email { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Địa chỉ")]
        public string diachi { get; set; }

        [Display(Name = "Tiêu đề")]
        public string tieude { get; set; }
        [Display(Name = "Ngày đặt hàng")]
        public Nullable<System.DateTime> ngaytao { get; set; }
        
        [Display(Name = "Tổng tiền")]
        public Nullable<double> tongtien { get; set; }
        [Display(Name = "Trạng thái đơn hàng")]
        public Nullable<int> idtrangthai { get; set; }
        public Nullable<int> idNgDung { get; set; }
        public Nullable<int> idNgGiaoHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual Nguoi_Dung Nguoi_Dung { get; set; }
        public virtual Nguoi_Giao_Hang Nguoi_Giao_Hang { get; set; }
        public virtual Trang_Thai Trang_Thai { get; set; }
    }
}
