//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanBachHoa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Nguoi_Dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguoi_Dung()
        {
            this.Don_Hang = new HashSet<Don_Hang>();
        }

        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Mã Người Dùng")]
        public int id { get; set; }
        [Required(ErrorMessage = "Tài khoản không được để trống")]
        [Display(Name = "Tài Khoản")]
        public string taikhoan { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        [StringLength(maximumLength: 50, MinimumLength = 6, ErrorMessage = "Mật Khẩu phải nhiều hơn 6 ký tự")]
        [Display(Name = "Mật Khẩu")]
        public string matkhau { get; set; }
        [Required(ErrorMessage = "Họ tên không được để trống")]
        [Display(Name = "Họ Và Tên")]
        public string ten { get; set; }
        [Required(ErrorMessage = "SDT không được để trống")]
        [StringLength(maximumLength: 10, MinimumLength = 6, ErrorMessage = "SDT không hợp lệ")]
        [Phone(ErrorMessage = "SDT phải là số")]
        [Display(Name = "SDT")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Email không được để trống")]
        [EmailAddress(ErrorMessage = "Không đúng định dạng Email")]
        [Display(Name = "Email")]
        public string email { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        [Display(Name = "Địa Chỉ")]
        public string diachi { get; set; }
        public Nullable<int> quyen { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_Hang> Don_Hang { get; set; }
    }
}
