//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanBachHoa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class San_Pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San_Pham()
        {
            this.Chi_Tiet_Don_Hang = new HashSet<Chi_Tiet_Don_Hang>();
        }

        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Mã sản phẩm")]
        public int id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Tên sản phẩm")]
        public string tenSP { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Hình")]
        public string hinh { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Giá")]
        public Nullable<double> gia { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Mô tả")]
        public string mota { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Trạng Thái")]
        public Nullable<bool> trangthai { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name = "Ngày đăng hình")]
        public Nullable<System.DateTime> ngaydanghinh { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public int idloaiSP { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]

        public int idNCC { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual Loai_San_Pham Loai_San_Pham { get; set; }
        public virtual Nha_Cung_Cap Nha_Cung_Cap { get; set; }
    }
}
